fails:Fiber.new creates a fiber from the given block
fails:Fiber.new raises an ArgumentError if called without a block
fails:Fiber.new does not invoke the block
fails:Fiber.new closes over lexical environments
fails:Fiber.new escapes an inner ensure block
fails:Fiber.new raises a SyntaxError when the block contains a retry statement
